name: Checks

on:
  push:
    branches:
  pull_request:

permissions:
  contents: read

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action
